import { KIND_META } from "@/lib/kinds";
import type { StepNode } from "@/lib/types";
import { flowTree, neighbours, type ExportSource } from "./flow";
import { toMermaid } from "./mermaid";

/** The flow as a readable document: overview, diagram, then every step in order. */
export function toMarkdown(source: ExportSource): string {
  const { title, rootQuery, summary, nodes, edges } = source;
  const { steps, subflows } = flowTree(nodes, edges);
  const out: string[] = [`# ${title}`, ""];

  if (rootQuery.trim().toLowerCase() !== title.trim().toLowerCase()) out.push(`> ${rootQuery}`, "");
  if (summary) out.push(summary, "");
  out.push("```mermaid", toMermaid(source), "```", "", "## Steps", "");

  const writeStep = (s: StepNode, number: string, level: number) => {
    const { inputs, outputs } = neighbours(s.id, nodes, edges);
    const kind = KIND_META[s.kind]?.label ?? "Step";
    out.push(`${"#".repeat(level)} ${number}. ${s.title} · ${kind}`, "", s.summary, "");
    if (inputs.length) out.push(`**Receives:** ${inputs.join(", ")}  `);
    if (outputs.length) out.push(`**Hands off:** ${outputs.join(", ")}  `);
    if (inputs.length || outputs.length) out.push("");
    if (s.details) out.push(s.details, "");
    if (s.keyPoints?.length) out.push(...s.keyPoints.map((p) => `- ${p}`), "");
    if (s.sources.length) out.push(`Sources: ${s.sources.map((src) => `[${src.title}](${src.url})`).join(" · ")}`, "");

    const sub = subflows.get(s.id);
    if (sub?.steps.length) {
      out.push(`${"#".repeat(Math.min(level + 1, 6))} ${sub.group.title}`, "");
      sub.steps.forEach((inner, i) => writeStep(inner, `${number}.${i + 1}`, Math.min(level + 2, 6)));
    }
  };

  steps.forEach((s, i) => writeStep(s, `${i + 1}`, 3));
  out.push("---", "", "_Made with Unfold. Generated by AI; check anything important._", "");
  return out.join("\n");
}
